
'''configs = [
        {'lm_id': '0_nolm_science_big_512',
         'output_path': 'class:0_nolm_science_big_512',
         'classification': True,
         'adaptive': False,
         'transfer_learning': False,
         'POS_tags': False,
         'bpe': False,
         'bpe_model_path': 'bpe/bpe_science_big.model',
         'masked_lm': False,
         'rnn': False,
         'crf': False,
         'datasets': 'semeval;krapivin;nus;inspec;kp20k',
         'lm_corpus_file': 'data_science_big.json',
         },
         #lm
        {'lm_id':'1_lm_science_big_512',
         'output_path': '',
         'classification': False,
         'adaptive': True,
         'transfer_learning': False,
         'POS_tags': False,
         'bpe':False,
         'bpe_model_path':'bpe/bpe_science_big.model',
         'masked_lm':False,
         'rnn': False,
         'crf': False,
         'datasets': 'semeval;krapivin;nus;inspec;kp20k',
         'lm_corpus_file':'data_science_big.json',
         },

        {'lm_id': '1_lm_science_big_512',
         'output_path': 'class:1_lm_science_big_512',
         'classification': True,
         'adaptive': False,
         'transfer_learning': True,
         'POS_tags': False,
         'bpe': False,
         'bpe_model_path': 'bpe/bpe_science_big.model',
         'masked_lm': False,
         'rnn': False,
         'crf': False,
         'datasets': 'semeval;krapivin;nus;inspec;kp20k',
         'lm_corpus_file': 'data_science_big.json',
         },

         #lm + rnn
         {'lm_id': '1_lm_science_big_512',
          'output_path': 'class:6_lm+rnn_science_big_512',
          'classification': True,
          'adaptive': False,
          'transfer_learning': True,
          'POS_tags': False,
          'bpe': False,
          'bpe_model_path': 'bpe/bpe_science_big.model',
          'masked_lm': False,
          'rnn': True,
          'crf': False,
          'datasets': 'semeval;krapivin;nus;inspec;kp20k',
          'lm_corpus_file': 'data_science_big.json',
          },

        # masked lm
        {'lm_id': '2_maskedlm_science_big_512',
         'output_path': '',
         'classification': False,
         'adaptive': True,
         'transfer_learning': False,
         'POS_tags': False,
         'bpe': False,
         'bpe_model_path': 'bpe/bpe_science_big.model',
         'masked_lm': True,
         'rnn': False,
         'crf': False,
         'datasets': 'semeval;krapivin;nus;inspec;kp20k',
         'lm_corpus_file': 'data_science_big.json',
         },

        {'lm_id': '2_maskedlm_science_big_512',
         'output_path': 'class:2_maskedlm_science_big_512',
         'classification': True,
         'adaptive': False,
         'transfer_learning': True,
         'POS_tags': False,
         'bpe': False,
         'bpe_model_path': 'bpe/bpe_science_big.model',
         'masked_lm': True,
         'rnn': False,
         'crf': False,
         'datasets': 'semeval;krapivin;nus;inspec;kp20k',
         'lm_corpus_file': 'data_science_big.json',
         },

        # lm + pos
        {'lm_id': '4_lm+pos_science_big_512',
         'output_path': '',
         'classification': False,
         'adaptive': True,
         'transfer_learning': False,
         'POS_tags': True,
         'bpe': False,
         'bpe_model_path': 'bpe/bpe_science_big.model',
         'masked_lm': False,
         'rnn': False,
         'crf': False,
         'datasets': 'semeval;krapivin;nus;inspec;kp20k',
         'lm_corpus_file': 'data_science_big.json',
         },

        {'lm_id': '4_lm+pos_science_big_512',
         'output_path': 'class:4_lm+pos_science_big_512',
         'classification': True,
         'adaptive': False,
         'transfer_learning': True,
         'POS_tags': True,
         'bpe': False,
         'bpe_model_path': 'bpe/bpe_science_big.model',
         'masked_lm': False,
         'rnn': False,
         'crf': False,
         'datasets': 'semeval;krapivin;nus;inspec;kp20k',
         'lm_corpus_file': 'data_science_big.json',
         },

        #lm + bpe + crf
        {'lm_id': '8_lm+bpe+rnn_science_512',
         'output_path': 'class:7_lm+bpe+crf_science_big_512',
         'classification': True,
         'adaptive': False,
         'transfer_learning': True,
         'POS_tags': False,
         'bpe': True,
         'bpe_model_path': 'bpe/bpe_science_big.model',
         'masked_lm': False,
         'rnn': False,
         'crf': True,
         'datasets': 'semeval;krapivin;nus;inspec;kp20k',
         'lm_corpus_file': 'data_science_big.json',
         },

         #lm + bpe
         {'lm_id': '8_lm+bpe+rnn_science_512',
          'output_path': 'class:3_lm+bp_science_big',
          'classification': True,
          'adaptive': False,
          'transfer_learning': True,
          'POS_tags': False,
          'bpe': True,
          'bpe_model_path': 'bpe/bpe_science_big.model',
          'masked_lm': False,
          'rnn': False,
          'crf': False,
          'datasets': 'semeval;krapivin;nus;inspec;kp20k',
          'lm_corpus_file': 'data_science_big.json',
          },
   ]'''

configs = [
         {'lm_id': '0_nolm_news_big_512',
          'output_path': 'class:0_nolm_news_big_512',
          'classification': True,
          'adaptive': False,
          'transfer_learning': False,
          'POS_tags': False,
          'bpe': False,
          'bpe_model_path': 'bpe/bpe_news_big.model',
          'masked_lm': False,
          'rnn': False,
          'crf': False,
          'datasets': 'duc;kptimes;jptimes',
          'lm_corpus_file': 'data_news_big.json',
          },
          
        #lm
        {'lm_id': '1_lm_news_big_512',
         'output_path': '',
         'classification': False,
         'adaptive': True,
         'transfer_learning': False,
         'POS_tags': False,
         'bpe':False,
         'bpe_model_path':'bpe/bpe_news_big.model',
         'masked_lm':False,
         'rnn': False,
         'crf': False,
         'datasets': 'duc;kptimes;jptimes',
         'lm_corpus_file':'data_news_big.json',
         },

        {'lm_id': '1_lm_news_big_512',
         'output_path': 'class:1_lm_news_big_512',
         'classification': True,
         'adaptive': False,
         'transfer_learning': True,
         'POS_tags': False,
         'bpe': False,
         'bpe_model_path': 'bpe/bpe_news_big.model',
         'masked_lm': False,
         'rnn': False,
         'crf': False,
         'datasets': 'duc;kptimes;jptimes',
         'lm_corpus_file': 'data_news_big.json',
         },
         
        #lm + rnn
        {'lm_id': '1_lm_news_big_512',
         'output_path': 'class:6_lm+rnn_news_big_512',
         'classification': True,
         'adaptive': False,
         'transfer_learning': True,
         'POS_tags': False,
         'bpe': False,
         'bpe_model_path': 'bpe/bpe_news_big.model',
         'masked_lm': False,
         'rnn': True,
         'crf': False,
         'datasets': 'duc;kptimes;jptimes',
         'lm_corpus_file': 'data_news_big.json',
         },
         
        # masked lm
        {'lm_id': '2_maskedlm_news_big_512',
         'output_path': '',
         'classification': False,
         'adaptive': True,
         'transfer_learning': False,
         'POS_tags': False,
         'bpe': False,
         'bpe_model_path': 'bpe/bpe_news_big.model',
         'masked_lm': True,
         'rnn': False,
         'crf': False,
         'datasets': 'duc;kptimes;jptimes',
         'lm_corpus_file': 'data_news_big.json',
         },
        {'lm_id': '2_maskedlm_news_big_512',
         'output_path': 'class:2_maskedlm_news_big_512',
         'classification': True,
         'adaptive': False,
         'transfer_learning': True,
         'POS_tags': False,
         'bpe': False,
         'bpe_model_path': 'bpe/bpe_news_big.model',
         'masked_lm': True,
         'rnn': False,
         'crf': False,
         'datasets': 'duc;kptimes;jptimes',
         'lm_corpus_file': 'data_news_big.json',
         },
         
         #lm + pos
        {'lm_id': '4_lm+pos_news_big_512',
         'output_path': '',
         'classification': False,
         'adaptive': True,
         'transfer_learning': False,
         'POS_tags': True,
         'bpe': False,
         'bpe_model_path': 'bpe/bpe_news_big.model',
         'masked_lm': False,
         'rnn': False,
         'crf': False,
         'datasets': 'duc;kptimes;jptimes',
         'lm_corpus_file': 'data_news_big.json',
         },
        {'lm_id': '4_lm+pos_news_big_512',
         'output_path': 'class:4_lm+pos_news_big_512',
         'classification': True,
         'adaptive': False,
         'transfer_learning': True,
         'POS_tags': True,
         'bpe': False,
         'bpe_model_path': 'bpe/bpe_news_big.model',
         'masked_lm': False,
         'rnn': False,
         'crf': False,
         'datasets': 'duc;kptimes;jptimes',
         'lm_corpus_file': 'data_news_big.json',
         },

        #lm + bp
        {'lm_id': '8_lm+bpe+rnn_news_512',
         'output_path': 'class:3_lm+bp_news_big_512',
         'classification': True,
         'adaptive': False,
         'transfer_learning': True,
         'POS_tags': False,
         'bpe': True,
         'bpe_model_path': 'bpe/bpe_news_big.model',
         'masked_lm': False,
         'rnn': False,
         'crf': False,
         'datasets': 'duc;kptimes;jptimes',
         'lm_corpus_file': 'data_news_big.json',
         },

        #lm + bp + crf
        {'lm_id': '8_lm+bpe+rnn_news_512',
         'output_path': 'class:7_lm+bpe+crf_news_big_512',
         'classification': True,
         'adaptive': False,
         'transfer_learning': True,
         'POS_tags': False,
         'bpe': True,
         'bpe_model_path': 'bpe/bpe_news_big.model',
         'masked_lm': False,
         'rnn': False,
         'crf': True,
         'datasets': 'duc;kptimes;jptimes',
         'lm_corpus_file': 'data_news_big.json',
         },
    ]

configs = [
 # masked lm
 {'lm_id': '2_maskedlm_news_big_512',
  'output_path': '',
  'classification': False,
  'adaptive': True,
  'transfer_learning': False,
  'POS_tags': False,
  'bpe': False,
  'bpe_model_path': 'bpe/bpe_news_big.model',
  'masked_lm': True,
  'rnn': False,
  'crf': False,
  'datasets': 'duc;kptimes;jptimes',
  'lm_corpus_file': 'data_news_big.json',
  },
 {'lm_id': '2_maskedlm_news_big_512',
  'output_path': 'class:2_maskedlm_news_big_512',
  'classification': True,
  'adaptive': False,
  'transfer_learning': True,
  'POS_tags': False,
  'bpe': False,
  'bpe_model_path': 'bpe/bpe_news_big.model',
  'masked_lm': True,
  'rnn': False,
  'crf': False,
  'datasets': 'duc;kptimes;jptimes',
  'lm_corpus_file': 'data_news_big.json',
  },

 # lm + pos
 {'lm_id': '4_lm+pos_news_big_512',
  'output_path': '',
  'classification': False,
  'adaptive': True,
  'transfer_learning': False,
  'POS_tags': True,
  'bpe': False,
  'bpe_model_path': 'bpe/bpe_news_big.model',
  'masked_lm': False,
  'rnn': False,
  'crf': False,
  'datasets': 'duc;kptimes;jptimes',
  'lm_corpus_file': 'data_news_big.json',
  },
 {'lm_id': '4_lm+pos_news_big_512',
  'output_path': 'class:4_lm+pos_news_big_512',
  'classification': True,
  'adaptive': False,
  'transfer_learning': True,
  'POS_tags': True,
  'bpe': False,
  'bpe_model_path': 'bpe/bpe_news_big.model',
  'masked_lm': False,
  'rnn': False,
  'crf': False,
  'datasets': 'duc;kptimes;jptimes',
  'lm_corpus_file': 'data_news_big.json',
  },

 # lm + bp
 {'lm_id': '8_lm+bpe+rnn_news_512',
  'output_path': 'class:3_lm+bp_news_big_512',
  'classification': True,
  'adaptive': False,
  'transfer_learning': True,
  'POS_tags': False,
  'bpe': True,
  'bpe_model_path': 'bpe/bpe_news_big.model',
  'masked_lm': False,
  'rnn': False,
  'crf': False,
  'datasets': 'duc;kptimes;jptimes',
  'lm_corpus_file': 'data_news_big.json',
  },

 # lm + bp + crf
 {'lm_id': '8_lm+bpe+rnn_news_512',
  'output_path': 'class:7_lm+bpe+crf_news_big_512',
  'classification': True,
  'adaptive': False,
  'transfer_learning': True,
  'POS_tags': False,
  'bpe': True,
  'bpe_model_path': 'bpe/bpe_news_big.model',
  'masked_lm': False,
  'rnn': False,
  'crf': True,
  'datasets': 'duc;kptimes;jptimes',
  'lm_corpus_file': 'data_news_big.json',
  },
]





